name: serene_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  smooth_page_indicator: ^1.2.1
  floating_frosted_bottom_bar: ^0.0.1
  pin_code_fields: ^8.0.1
  http: ^1.2.0
  shared_preferences: ^2.2.3
  syncfusion_flutter_gauges: ^28.2.11
  jwt_decoder: ^2.0.1
  shimmer: ^3.0.0
  url_launcher: ^6.2.0
  just_audio: ^0.9.22
  just_audio_background: ^0.0.1-beta.16
  audio_service: ^0.18.10
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  youtube_explode_dart: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/auth/
    - assets/images/questionnaire/
    - assets/images/home/
    - assets/images/home/menu/
    - assets/images/home/detail/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700